### ISSUE TITLE
PortAudio will not "Make"

### ISSUE THREAD

**Issue by Piflyer** [alexa/alexa-smart-screen-sdk#11] opened 2019-12-15 14:54 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Portaudio will not "make", outputs this `if test -n "" ; then for dir in ""; do make -C $dir all; done ; fi`
## What is the expected behavior?

It should have be able to "make"
## What behavior are you observing?

Crashing
## Provide the steps to reproduce the issue, if applicable:

run `cd /home/pi/sdk_folder/third-party

wget -c http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
tar zxf pa_stable_v190600_20161030.tgz

cd portaudio
./configure --without-jack

make`
### What version of the AVS Device SDK are you using?
      Latest

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by powj** [comment] 2019-12-16 19:11
Hi @Piflyer , this sounds like an environment issue. Can you post the full output from the `configure` and `make` commands, as well as the output from `env`.

**Comment by eeduwj** [comment] 2019-12-23 20:35
This comment is unrelated to Portaudio but I saw that you answered "Latest" to the question "What version of the AVS Device SDK are you using?"

The latest AVS Device SDK is version 1.17 (as of December 2019). The Smart Screen SDK 2.0 does not work with version 1.17 (you can make it work but not just by following the installation instructions). The Smart Screen SDK version 2.0 has been verified with the AVS Device SDK version 1.15. Please use 2.0 together with 1.15.

**Comment by lynx-arul** [comment] 2019-12-30 18:32
Closing this due to inactivity. Please feel free to re-open if you encounter further problems. 
Thanks!

**Comment by Sindar-sudo** [comment] 2021-01-12 17:48
I ran into the same issue, following the official guide here: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html
So the issue is basically blindly copying the commands... :)
It says  cd ../third-party before commands to download and make portaudio, however, since this is not an absolute path You might be in a different directory.
Manually navigating to /my_project/third-party/portaudio and make-ing it there, works better.

**Comment by vkarpuram** [comment] 2021-01-12 19:29
Closing out this since information provided by @Sindar-sudo is a resolution to the issue

**Closed by vkarpuram** 2021-01-12 19:29 UTC
