### ISSUE TITLE
Memory leak investigation for GUI

### ISSUE THREAD

**Issue by oscar1372** [alexa/alexa-smart-screen-sdk#84] opened 2021-03-31 15:33 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We notice GUI has memory leak issue during playing music or APLRenderWindow case. the memory will keep to increase a little when each interaction even if force garbage collection.

Here is snapshot can be analyzed.
[Heap-20210331T231521-MusicTest.heapsnapshot.tar.gz](https://github.com/alexa/alexa-smart-screen-sdk/files/6237692/Heap-20210331T231521-MusicTest.heapsnapshot.tar.gz)
It has two files:
Heap-20210331T231457-beforeMusic.heapsnapshot is snapshot for step3
Heap-20210331T231521-AfterMusic.heapsnapshot is snapshot for step9

## What is the expected behavior?

Should be keep in one level after multiple interaction.

## What behavior are you observing?

It will keep to increase

## Provide the steps to reproduce the issue, if applicable:

1. Open devTool on Chromium and choose memory tab
2. Press "Garbage Collection" icon
3. Take Snapshot
4. Press A and Say "Play Kacey Musgraves on iHeartRadio"
5. Wait 20 seconds
6. Press A and Say "Stop"
7. Press ESC key
8. Press "Garbage Collection" icon and choose memory tab
9. Take Snapshot

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [x] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by powj** [comment] 2021-04-07 17:02
Hi @oscar1372 , Thank you for raising this issue, we are looking into this to identify the cause of this behavior and we will provide an update here once we have any further information to share.

**Comment by oscar1372** [comment] 2021-04-12 16:22
@powj , I upload another heap snapshot which modifies the mode to "development" in webpack.config.js to print more information.

Here is new one
[Heap-20210331T231521-MusicTest.heapsnapshot.tar.gz](https://github.com/alexa/alexa-smart-screen-sdk/files/6298132/Heap-20210331T231521-MusicTest.heapsnapshot.tar.gz)
it has three files:
Heap-20210412T235800-initBeforeMusic.heapsnapshot in snapshot for step3
Heap-20210412T235750-firstAfterMusic.heapsnapshot in snapshot for step9
Heap-20210412T235835-secondAfterＭusic.heapsnapshot in snapshot which repeat step 4~8 again and do for step9.

I try to compare allocated between Heap-20210412T235750 and Heap-20210412T235835. I think it may be resource doesn't release clear in this.renderer.destory() in APLRendererWindow.tsx.

I notice top and componentIdMap has reference event if Element is detached in index.js. Does it the point of memory leak?

**Comment by powj** [comment] 2021-04-12 21:21
@oscar1372 , I have been able to reproduce this and it will be investigated by the appropriate team. I will pass on the latest snapshots which you have provided to aid the investigation.

Thanks for your contribution to help improve the Alexa Smart Screen SDK!

**Comment by oscar1372** [comment] 2021-04-26 13:40
@powj , Could I know is there any update for memory leak of GUI? Because the problem may needs to check into [ apl-client-js](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/Alexa/APLClientLibrary/apl-client-js/index.js), I can not check in deep if I doesn't know the meaning of variable.

**Comment by nguymi91** [comment] 2021-05-05 15:01
@oscar1372 ,

It's on our plan. Please expect a fix for that issue in the near future.

Thanks,
Mike

**Closed by nguymi91** 2021-05-05 15:01 UTC

**Comment by Jinglouyan** [comment] 2022-03-04 13:20
@nguymi91 Hi , this  issue has been fixed yet ? I encountered the same problem with the Smart Screen version 2.8, Device SDK version 1.26

**Comment by powj** [comment] 2022-03-04 19:41
Hi @Jinglouyan, the original issue was resolved in the 1.7 release of APLClient, if after upgrading to the latest version of the smart screen SDK you still see a memory leak then please create a new issue. 

If you have identified the leak as coming from the APL Client/viewhost then please raise the issue in the APLClient github project https://github.com/alexa/apl-client-library .

**Comment by Jinglouyan** [comment] 2022-03-05 09:03
@powj Hi , can you please point out the specific version of this issue fixed ? I encountered the same problem and my machine can not upgrade version right now . 
Here is version information:
alexa smart screen sdk : 2.8.0
apl-client-library:1.7.2
apl-core-library:1.7.1
avs-device-sdk:1.25.0
Can you please check it for me ? 
If it do have problems , what could I do to remedy it without change version .
Looking forward to your reply , thanks.

**Comment by Jinglouyan** [comment] 2022-03-07 06:22
@powj By using the devtools , I found that the web audio context and web audio destination objects were created but not released .

**Comment by powj** [comment] 2022-03-07 22:37
@Jinglouyan Can you please list the steps which you are following so that I can reproduce this issue - from what you are describing it sounds like this issue may be different than the original issue.

**Comment by Jinglouyan** [comment] 2022-03-08 02:19
@powj I create a new issue to descripe this problem . Please check it . https://github.com/alexa/alexa-smart-screen-sdk/issues/126
