### ISSUE TITLE
Music playback - stop - crash observed with error!

### ISSUE THREAD

**Issue by sakthisg** [alexa/alexa-smart-screen-sdk#65] opened 2020-12-10 14:14 UTC
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Stop command - getting errors and SIGABORT

## What is the expected behavior?
Should run normally.

## What behavior are you observing?
Application crashes.
There are errors:

AlexaPresentation:processExecuteCommandsResultExecutorFailed:reason=asked to process missing directive,messageId=RenderPlayerInfo
[2020-12-10 19:14:39.261] 2020-12-10 13:44:38.454 [ 1b] E CapabilityAgent:sendExceptionEncounteredAndReportFailed:reason=infoNotFound
[2020-12-10 19:14:39.261] 2020-12-10 13:44:38.464 [ 1b] E AlexaPresentation:processExecuteCommandsResultExecutorFailed:reason=asked to process missing directive,messageId=RenderPlayerInfo

SIGABORT:
SIGABRT: software abort

Backtrace and logs:
[PR_TO_SSSDK.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/5673285/PR_TO_SSSDK.txt)
[backtrace.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/5673302/backtrace.txt)

## Provide the steps to reproduce the issue, if applicable:
Play Songs from Amazon Music . Pause it .

## Tell us about your environment:
Modified the sampleApp...
### What version of the AVS Device SDK are you using?
AVS SDK version 1.20.1, APL version 1.3.3 and SS SDK version 2.2.1
### Tell us what hardware you're using:

Crosscompiled

### Tell us about your OS (Type & version):
- [ ] Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
-
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by VaruPan** [comment] 2020-12-10 19:33
Hi @sakthisg,

Thanks a lot for reaching out and providing the backtrace, it seems like GUI layer might be sending incorrect value with `updateCursorPosition` message. From the backtrace looking at frame 6 i.e. `APLClient::AplCoreConnectionManager::handleUpdateCursorPosition`, it is attempting to parse payload and rapidjson could be causing this error. 

When you hit the crash, can you go to the frame and try to fetch the payload by printing them to logs (the symbols are missing currently), that will give more information. Just as a reference, rapidjson does not implicitly assumes integer value to be a subset of double causing some asserts.

**Comment by zsubas** [comment] 2021-01-05 00:40
Closing this issue due to inactivity. Feel free to reopen it if you're still experiencing the issue.

**Comment by zsubas** [comment] 2021-01-06 18:13
-DRAPIDJSON_MEM_OPTIMIZATION=OFF is only used for AVS SDK build. 

In latest version of smart screen sdk, we merged the rapidjson libraries. Right now we are referring avs sdk's rapidjson and apl-core's rapidjson: https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/mac-os.html
We don't have a rapidjson library under smart-screen-sdk anymore.

I would suggest you to update the smart screen sdk to the latest version if possible. If not, please share the details of the crash (at which scenario it crashes, detailed logs) so we can investigate further.

**Comment by sakthisg** [comment] 2021-01-07 05:49
Thanks for the inputs.  Most of the times the core is not getting generated. 
In our device we  are using:
AVS SDK version 1.20.1, APL version 1.3.3 and SS SDK version 2.2.1

For the above version used can you please confirm the rapid json flags to be used?
Command Issued:
Ask Alexa for the Wikipedia entry on Grace Hopper. 
After that if we press back key in our device. 

/home/kumar.jagadish/commit_userid/alexa/prebuilts/mvoiceapp/avs/prebuilts/include/rapidjson/document.h:1692: double rapidjson::GenericValue<Encoding, Allocator>::GetDouble() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]: Assertion `IsNumber()' failed.

**Comment by karpuv** [comment] 2021-01-11 07:59
Hello @sakthisg,

The rapidjson flag to use on AVS is: -DRAPIDJSON_MEM_OPTIMIZATION and the flag to be used on Alexa smart screen sdk is: -DAPLCORE_RAPIDJSON_INCLUDE_DIR. 

As for the crash, have you been able to fetch the payload through the backtrace as @VaruPan suggested? This will help us debug further

**Comment by Jagadish-Bommisetty** [comment] 2021-01-12 06:14
Hi @VaruPan/@karpuv 
We fetch the payload from APLClient::AplCoreConnectionManager::handleUpdateCursorPosition. The paylaod is as follows,

**Payload and crash**
[2021-01-11 22:50:42.007] [smartscreenSDK - AplCoreConnectionManager] handleUpdateCursorPosition payload {"x":null,"y":null}
[2021-01-11 22:50:42.007] TpvSmartScreenAlexaApp: /home/kumar.jagadish/add_prints_updateCursorPosition/alexa/prebuilts/mvoiceapp/avs/prebuilts/include/rapidjson/document.h:1692: double rapidjson::GenericValue<Encoding, Al
[2021-01-11 22:50:42.023] locator>::GetDouble() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]: Assertion `IsNumber()' failed. 

**scenario:**
while GUI page loaded, pressed the back key and home key on our device.

**Observation:**
seen that x and y co-ordinates in payload is null. since in the code, GetFloat() API used to read the co-ordinates from payload.  it is eventually causing the crash.

can we block to send this payload to APL. if yes, is there any regression or side effect with that.
if not, can you give any suggestion to avoid this issue.

BTW, may i know how this cursorPosition payload is used in APL..?

**Comment by VaruPan** [comment] 2021-01-13 02:04
Hi @Jagadish-Bommisetty,

The rendering engine needs to know the cursor position to respond correctly to clicks/hover/swiping events. I suspect blocking these messages may result in missed events. I encourage you to post this question on [rendering engine](https://github.com/alexa/apl-core-library) project for further clarifications. 

You can also investigate on - why the browser is sending null cursor positions? I can confirm that we do not see null values in payload on reference platforms.

Thank you for your contribution to the Alexa Smart Screen SDK!

**Closed** 2021-01-21 23:09 UTC
